# Generated by Django 3.1 on 2020-08-20 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_auto_20200820_1223'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Modules',
            new_name='Module',
        ),
    ]
