# Generated by Django 3.1 on 2020-08-20 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('module', '0004_auto_20200820_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='modules',
        ),
        migrations.AlterField(
            model_name='userprogram',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
