# Generated by Django 3.1 on 2020-08-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0005_auto_20200820_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='description',
            field=models.TextField(default='', max_length=555),
        ),
    ]
