# Generated by Django 3.1 on 2020-08-25 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0006_program_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogram',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program', to='module.program'),
        ),
    ]
