# Generated by Django 3.1 on 2020-08-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0008_purchasedprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedprogram',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='purchasedprogram',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='purchasedprogram',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='purchasedprogram',
            name='total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='purchasedprogram',
            name='zipcode',
            field=models.IntegerField(default=0),
        ),
    ]
